### ISSUE TITLE
An issue with the monad documentation

### ISSUE THREAD

**Issue by GetContented** [Daniel-Diaz/hatex-guide#14]
There is a problem with the monad.htgx documentation, but I can't repair it.

It currently reads:

    ##The Writer Monad##
    Fixed a monoid \{M\}, the \{M\}-writer monad is just all possible pairs of elements from \{M\}
    and elements from other types. Thus, the Haskell declaration is as follows\f
    Some authors write it using tuples, like this: \{data W m a = W (a,m)\}.\f:

But "Fixed a monoid M, the M-writer monad..." doesn't make sense.

What is it supposed to mean? (Could you please use different words so I can extract your meaning).

**Comment by Daniel-Diaz** [comment]
For any given monoid M...

**Comment by GetContented** [comment]
Ahhhh :) ok. That makes a lot of sense. I guess you can change it then? :)

**Comment by GetContented** [comment]
Actually, I just adjusted the files in the PR, so should be good to go now.
